title: Markdown 4 lyfe
description: Test test test
theme: just-the-docs

url: https://pj-woz.github.io/justice-the-docs

logo: /Images/IMG_20200401_210429.jpg

favicon_ico: /Images/6cf.jpg

aux_links:
  Template Repository: https://github.com/pj-woz/justice-the-docs
