title: Markdown 4 lyfe
description: Test test test
theme: just-the-docs

url: https://pj-woz.github.io/justice-the-docs

logo: /Images/translatorion_logo_kolor.png

favicon_ico: /Images/6cf.jpg

heading_anchors: true

color_scheme: dark

aux_links:
  Template Repository: https://github.com/pj-woz/justice-the-docs
  
footer_content: "KOPIRAJTY!"

back_to_top: true

back_to_top_text: "Back to WORK!"
